// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Data;

#nullable disable

namespace Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230207082152_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Server.Models.Position", b =>
                {
                    b.Property<int>("idposition")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("position_code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("position_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("title_id")
                        .HasColumnType("int");

                    b.HasKey("idposition");

                    b.HasIndex("position_code")
                        .IsUnique();

                    b.HasIndex("position_name")
                        .IsUnique();

                    b.ToTable("positions");
                });

            modelBuilder.Entity("Server.Models.Title", b =>
                {
                    b.Property<int>("idtitle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("title_code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("title_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("idtitle");

                    b.HasIndex("title_code")
                        .IsUnique();

                    b.HasIndex("title_name")
                        .IsUnique();

                    b.ToTable("titles");
                });
#pragma warning restore 612, 618
        }
    }
}
